# Generated by Django 4.1.5 on 2023-01-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='colored_logo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
